//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dizi_World.Service_Reference_2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_Reference_2.Sql_WebServiceSoap")]
    public interface Sql_WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login_dogrula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int login_dogrula(string kulad, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login_dogrula", ReplyAction="*")]
        System.Threading.Tasks.Task<int> login_dogrulaAsync(string kulad, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/giris_bilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet giris_bilgileri(string kulad, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/giris_bilgileri", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> giris_bilgileriAsync(string kulad, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kullanici_kayit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int kullanici_kayit(string ad, string soyad, string kulad, string sifre, string email, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kullanici_kayit", ReplyAction="*")]
        System.Threading.Tasks.Task<int> kullanici_kayitAsync(string ad, string soyad, string kulad, string sifre, string email, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dizi_arama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet dizi_arama(string deger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dizi_arama", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> dizi_aramaAsync(string deger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kategoriler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet kategoriler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kategoriler", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> kategorilerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/diziler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet diziler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/diziler", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> dizilerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/diziler_genelkategori", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet diziler_genelkategori(int genelkatid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/diziler_genelkategori", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> diziler_genelkategoriAsync(int genelkatid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/diziler_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet diziler_id(int dizi_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/diziler_id", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> diziler_idAsync(int dizi_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kategori_diziler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet kategori_diziler(int kategori_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kategori_diziler", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> kategori_dizilerAsync(int kategori_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/slider", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet slider();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/slider", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> sliderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/genel_kategoriler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet genel_kategoriler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/genel_kategoriler", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> genel_kategorilerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sezonlar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet sezonlar(int dizi_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sezonlar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> sezonlarAsync(int dizi_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bolumler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bolumler(int dizi_id, int sezon_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bolumler", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> bolumlerAsync(int dizi_id, int sezon_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bolumler_izle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bolumler_izle(int dizi_id, int sezon_id, int bolum_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bolumler_izle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> bolumler_izleAsync(int dizi_id, int sezon_id, int bolum_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/watch_bolum_id_getir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet watch_bolum_id_getir(int dizi_id, int sezon_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/watch_bolum_id_getir", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> watch_bolum_id_getirAsync(int dizi_id, int sezon_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/user_list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet user_list(int kul_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/user_list", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> user_listAsync(int kul_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/user_info_get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet user_info_get(int kul_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/user_info_get", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> user_info_getAsync(int kul_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/user_info_p_update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int user_info_p_update(int kul_id, string ad, string soyad, string kulad, string sifre, string email, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/user_info_p_update", ReplyAction="*")]
        System.Threading.Tasks.Task<int> user_info_p_updateAsync(int kul_id, string ad, string soyad, string kulad, string sifre, string email, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/user_info_update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int user_info_update(int kul_id, string ad, string soyad, string kulad, string email, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/user_info_update", ReplyAction="*")]
        System.Threading.Tasks.Task<int> user_info_updateAsync(int kul_id, string ad, string soyad, string kulad, string email, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listeye_ekle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int listeye_ekle(int kul_id, int dizi_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listeye_ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<int> listeye_ekleAsync(int kul_id, int dizi_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iletisim_ekle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int iletisim_ekle(string ad, string soyad, string email, string tel, string tur, string mesaj, int kul_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iletisim_ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<int> iletisim_ekleAsync(string ad, string soyad, string email, string tel, string tur, string mesaj, int kul_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Sql_WebServiceSoapChannel : Dizi_World.Service_Reference_2.Sql_WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Sql_WebServiceSoapClient : System.ServiceModel.ClientBase<Dizi_World.Service_Reference_2.Sql_WebServiceSoap>, Dizi_World.Service_Reference_2.Sql_WebServiceSoap {
        
        public Sql_WebServiceSoapClient() {
        }
        
        public Sql_WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Sql_WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sql_WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Sql_WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int login_dogrula(string kulad, string sifre) {
            return base.Channel.login_dogrula(kulad, sifre);
        }
        
        public System.Threading.Tasks.Task<int> login_dogrulaAsync(string kulad, string sifre) {
            return base.Channel.login_dogrulaAsync(kulad, sifre);
        }
        
        public System.Data.DataSet giris_bilgileri(string kulad, string sifre) {
            return base.Channel.giris_bilgileri(kulad, sifre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> giris_bilgileriAsync(string kulad, string sifre) {
            return base.Channel.giris_bilgileriAsync(kulad, sifre);
        }
        
        public int kullanici_kayit(string ad, string soyad, string kulad, string sifre, string email, string tel) {
            return base.Channel.kullanici_kayit(ad, soyad, kulad, sifre, email, tel);
        }
        
        public System.Threading.Tasks.Task<int> kullanici_kayitAsync(string ad, string soyad, string kulad, string sifre, string email, string tel) {
            return base.Channel.kullanici_kayitAsync(ad, soyad, kulad, sifre, email, tel);
        }
        
        public System.Data.DataSet dizi_arama(string deger) {
            return base.Channel.dizi_arama(deger);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> dizi_aramaAsync(string deger) {
            return base.Channel.dizi_aramaAsync(deger);
        }
        
        public System.Data.DataSet kategoriler() {
            return base.Channel.kategoriler();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> kategorilerAsync() {
            return base.Channel.kategorilerAsync();
        }
        
        public System.Data.DataSet diziler() {
            return base.Channel.diziler();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> dizilerAsync() {
            return base.Channel.dizilerAsync();
        }
        
        public System.Data.DataSet diziler_genelkategori(int genelkatid) {
            return base.Channel.diziler_genelkategori(genelkatid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> diziler_genelkategoriAsync(int genelkatid) {
            return base.Channel.diziler_genelkategoriAsync(genelkatid);
        }
        
        public System.Data.DataSet diziler_id(int dizi_id) {
            return base.Channel.diziler_id(dizi_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> diziler_idAsync(int dizi_id) {
            return base.Channel.diziler_idAsync(dizi_id);
        }
        
        public System.Data.DataSet kategori_diziler(int kategori_id) {
            return base.Channel.kategori_diziler(kategori_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> kategori_dizilerAsync(int kategori_id) {
            return base.Channel.kategori_dizilerAsync(kategori_id);
        }
        
        public System.Data.DataSet slider() {
            return base.Channel.slider();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> sliderAsync() {
            return base.Channel.sliderAsync();
        }
        
        public System.Data.DataSet genel_kategoriler() {
            return base.Channel.genel_kategoriler();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> genel_kategorilerAsync() {
            return base.Channel.genel_kategorilerAsync();
        }
        
        public System.Data.DataSet sezonlar(int dizi_id) {
            return base.Channel.sezonlar(dizi_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> sezonlarAsync(int dizi_id) {
            return base.Channel.sezonlarAsync(dizi_id);
        }
        
        public System.Data.DataSet bolumler(int dizi_id, int sezon_id) {
            return base.Channel.bolumler(dizi_id, sezon_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> bolumlerAsync(int dizi_id, int sezon_id) {
            return base.Channel.bolumlerAsync(dizi_id, sezon_id);
        }
        
        public System.Data.DataSet bolumler_izle(int dizi_id, int sezon_id, int bolum_id) {
            return base.Channel.bolumler_izle(dizi_id, sezon_id, bolum_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> bolumler_izleAsync(int dizi_id, int sezon_id, int bolum_id) {
            return base.Channel.bolumler_izleAsync(dizi_id, sezon_id, bolum_id);
        }
        
        public System.Data.DataSet watch_bolum_id_getir(int dizi_id, int sezon_id) {
            return base.Channel.watch_bolum_id_getir(dizi_id, sezon_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> watch_bolum_id_getirAsync(int dizi_id, int sezon_id) {
            return base.Channel.watch_bolum_id_getirAsync(dizi_id, sezon_id);
        }
        
        public System.Data.DataSet user_list(int kul_id) {
            return base.Channel.user_list(kul_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> user_listAsync(int kul_id) {
            return base.Channel.user_listAsync(kul_id);
        }
        
        public System.Data.DataSet user_info_get(int kul_id) {
            return base.Channel.user_info_get(kul_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> user_info_getAsync(int kul_id) {
            return base.Channel.user_info_getAsync(kul_id);
        }
        
        public int user_info_p_update(int kul_id, string ad, string soyad, string kulad, string sifre, string email, string tel) {
            return base.Channel.user_info_p_update(kul_id, ad, soyad, kulad, sifre, email, tel);
        }
        
        public System.Threading.Tasks.Task<int> user_info_p_updateAsync(int kul_id, string ad, string soyad, string kulad, string sifre, string email, string tel) {
            return base.Channel.user_info_p_updateAsync(kul_id, ad, soyad, kulad, sifre, email, tel);
        }
        
        public int user_info_update(int kul_id, string ad, string soyad, string kulad, string email, string tel) {
            return base.Channel.user_info_update(kul_id, ad, soyad, kulad, email, tel);
        }
        
        public System.Threading.Tasks.Task<int> user_info_updateAsync(int kul_id, string ad, string soyad, string kulad, string email, string tel) {
            return base.Channel.user_info_updateAsync(kul_id, ad, soyad, kulad, email, tel);
        }
        
        public int listeye_ekle(int kul_id, int dizi_id) {
            return base.Channel.listeye_ekle(kul_id, dizi_id);
        }
        
        public System.Threading.Tasks.Task<int> listeye_ekleAsync(int kul_id, int dizi_id) {
            return base.Channel.listeye_ekleAsync(kul_id, dizi_id);
        }
        
        public int iletisim_ekle(string ad, string soyad, string email, string tel, string tur, string mesaj, int kul_id) {
            return base.Channel.iletisim_ekle(ad, soyad, email, tel, tur, mesaj, kul_id);
        }
        
        public System.Threading.Tasks.Task<int> iletisim_ekleAsync(string ad, string soyad, string email, string tel, string tur, string mesaj, int kul_id) {
            return base.Channel.iletisim_ekleAsync(ad, soyad, email, tel, tur, mesaj, kul_id);
        }
    }
}
